# Generated by Django 3.2.17 on 2023-02-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adres',
            new_name='address',
        ),
    ]
